name: Java CI with Maven (pom)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (Simulado)
        run: echo "Compilando con Maven... ¡Simulación exitosa!"

      - name: Update dependency graph (Simulado)
        run: echo "Actualizando grafo de dependencias... ¡Simulación exitosa!"

    
